In [1]:
import numpy as np

In [3]:
# 1.

A = np.array([
    [[23,50],[7,12]], [[57,67],[99,43]],
    [[75,21], [57,12]], [[87, 26],[18,84]]])

A

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [7]:
# 2 Lakukan perkalian terhadap matrix berikut

A1 = np.array([[23,50,19], [7,12,109], [57,67,98]])
B = np.array([17,22,19])

A1.dot(B)

array([1852, 2454, 4305])

In [13]:
# 3. Lakukan transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

C = np.array([[23,50,19], [7,12,109], [57,67,98]])
C.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [11]:

from numpy.linalg import inv, det
# menghitung determinan
det(C)

131344.0000000002

In [14]:
# menghitung invers
inv(C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])